In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/ipl.csv')
df.head()

,team1,team2,match_date,toss_winner,toss_decision,winner,player_of_match,venue,city,team1_players,team2_players,season,match_number,match_type,result,result_margin,target_runs,target_overs,super_over
0,Royal Challengers Bangalore,Kolkata Knight Riders,2008-04-18,Royal Challengers Bangalore,field,Kolkata Knight Riders,BB McCullum,M Chinnaswamy Stadium,Bangalore,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",1,1,League,runs,140.0,223.0,20.0,N
1,Kings XI Punjab,Chennai Super Kings,2008-04-19,Chennai Super Kings,bat,Chennai Super Kings,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Chandigarh,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",1,2,League,runs,33.0,241.0,20.0,N
2,Delhi Daredevils,Rajasthan Royals,2008-04-19,Rajasthan Royals,bat,Delhi Daredevils,MF Maharoof,Feroz Shah Kotla,Delhi,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...",1,3,League,wickets,9.0,130.0,20.0,N
3,Mumbai Indians,Royal Challengers Bangalore,2008-04-20,Mumbai Indians,bat,Royal Challengers Bangalore,MV Boucher,Wankhede Stadium,Mumbai,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...",1,4,League,wickets,5.0,166.0,20.0,N
4,Kolkata Knight Riders,Deccan Chargers,2008-04-20,Deccan Chargers,bat,Kolkata Knight Riders,DJ Hussey,Eden Gardens,Kolkata,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...",1,5,League,wickets,5.0,111.0,20.0,N

In [3]:
df.isnull().sum()

team1               0
team2               0
match_date          0
toss_winner         0
toss_decision       0
winner             23
player_of_match     0
venue               0
city               51
team1_players       0
team2_players       0
season              0
match_number        0
match_type          0
result              0
result_margin      23
target_runs         6
target_overs        6
super_over          0
dtype: int64

In [4]:
df['winner'] = df['winner'].fillna('No Result')
df['city'] = df['city'].fillna('Unknown')

df['result_margin'] = df['result_margin'].fillna(df['result_margin'].median())
df['target_runs'] = df['target_runs'].fillna(df['target_runs'].median())
df['target_overs'] = df['target_overs'].fillna(df['target_overs'].median())

In [5]:
df.isnull().sum()

team1              0
team2              0
match_date         0
toss_winner        0
toss_decision      0
winner             0
player_of_match    0
venue              0
city               0
team1_players      0
team2_players      0
season             0
match_number       0
match_type         0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   team1            1169 non-null   object
 1   team2            1169 non-null   object
 2   match_date       1169 non-null   object
 3   toss_winner      1169 non-null   object
 4   toss_decision    1169 non-null   object
 5   winner           1169 non-null   object
 6   player_of_match  1169 non-null   object
 7   venue            1169 non-null   object
 8   city             1169 non-null   object
 9   team1_players    1169 non-null   object
 10  team2_players    1169 non-null   object
 11  season           1169 non-null   int64
 12  match_number     1169 non-null   int64
 13  match_type       1169 non-null   object
 14  result           1169 non-null   object
 15  result_margin    1169 non-null   float64
 16  target_runs      1169 non-null   float64
 17  target_overs     1169 non-null   float64
 18  super_over       1169 non-null   object
dtypes: float64(3), int64(2), object(14)
memory usage: 173.7+ KB

In [7]:
df['toss_match_win'] = (df['toss_winner'] == df['winner'])

In [8]:
toss_win_probability = df['toss_match_win'].mean()

print("Toss winner win probability:", toss_win_probability)

Toss winner win probability: 0.5055603079555175

In [9]:
# H₀ (Null Hypothesis): Toss winners do not have a higher match win probability than 50%
# H₁ (Alternative Hypothesis): Toss winners have a higher match win probability than 50%.

In [10]:
# One-Proportion Z-Test
from statsmodels.stats.proportion import proportions_ztest

successes = df['toss_match_win'].sum()
total_matches = len(df)

z_stat, p_value = proportions_ztest(
    count=successes,
    nobs=total_matches,
    value=0.5,
    alternative='larger'
)

print("Z-statistic:", z_stat)
print("P-value:", p_value)

Z-statistic: 0.3802445101578672
P-value: 0.35188196089898355

In [11]:
alpha = 0.05

if p_value < alpha:
    print("Toss winners have a higher match win probability than 50%.")
else:
    print("Toss winners do not have a higher match win probability than 50%")

Toss winners do not have a higher match win probability than 50%